### ISSUE TITLE
Add task for managing code deployment

### ISSUE THREAD

**Issue by zbal** [wiredcraft-ops/role-wcl-strongloop#3]
Add several defaults:
- `strongloop_install`: `true`
- `strongloop_deploy` or `build`: `false

In the `tasks` folder:
- rename `debian` and `redhat` to install_debian ..
- create a new build / deploy.yml with the steps

In the `main.yml`:
- update to incude the new install_xxx, and add the `when: strongloop_install is defined and strongloop_install`
- include the `deploy.yml` with `when: strongloop_deploy`

---

Bonus:
- figure out how we could manage multiple services and set of distinct env vars on a same box
- think that we prompt users for which version to deploy
- think that we may not want to (re) deploy all the services on the box every time

eg. 

```
strongloop_services:
  - id: v1.0
    update: true
    repo: githuh/..
    version: v0.3.4
    env:
      env

  - id: v2.0
    update: true
    repo: githuh/..
    version: v0.4.1
    env:
      env
```
